In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

1) One Hot Encoding

In [3]:
dataset=pd.read_csv('titanic_train.csv')
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
dataset['Sex'].unique()

array(['male', 'female'], dtype=object)

In [4]:
Sex_converted_variable=pd.get_dummies(dataset['Sex'],drop_first=True).head()

In [5]:
Sex_converted_variable

male
0   True
1  False
2  False
3  False
4   True

In [5]:
dataset=pd.concat([dataset,Sex_converted_variable],axis=1)
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked   male  
0      0         A/5 21171   7.2500   NaN        S   True  
1      0          PC 17599  71.2833   C85        C  False  
2      0  STON/O2. 3101282   7.9250   NaN        S  False  
3      0            113803  53.1000  C123        S  False  
4      0            373450   8.0500   NaN        S   True

In [6]:
dataset.drop('Sex',axis=1,inplace=True)

In [7]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                           Allen, Mr. William Henry  35.0      0      0   

             Ticket     Fare Cabin Embarked   male  
0         A/5 21171   7.2500   NaN        S   True  
1          PC 17599  71.2833   C85        C  False  
2  STON/O2. 3101282   7.9250   NaN        S  False  
3            113803  53.1000  C123        S  False  
4            373450   8.0500   NaN        S   True

In [2]:
df=pd.read_csv('data-one-hot-encoder.csv')

In [3]:
df.head()

Id Colour Country
0   1    Red     USA
1   2    Red     USA
2   3   Blue      UK
3   4  Green  Canada
4   5  Green  Canada

In [4]:
df.dtypes

Id          int64
Colour     object
Country    object
dtype: object

In [6]:
df['Colour'].unique()

array(['Red', 'Blue', 'Green'], dtype=object)

In [7]:
df['Country'].unique()

array(['USA', 'UK', 'Canada'], dtype=object)

In [8]:
ohe=OneHotEncoder()

In [9]:
feature_array = ohe.fit_transform(df[["Colour","Country"]]).toarray()

In [10]:
print(feature_array)

[[0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0.]
 ...
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 1.]]


In [11]:
feature_labels = ohe.categories_

In [12]:
feature_labels=np.array(feature_labels).ravel()

In [13]:
print(feature_labels)

['Blue' 'Green' 'Red' 'Canada' 'UK' 'USA']


In [14]:
pd.DataFrame(feature_array,columns=feature_labels)

Blue  Green  Red  Canada   UK  USA
0     0.0    0.0  1.0     0.0  0.0  1.0
1     0.0    0.0  1.0     0.0  0.0  1.0
2     1.0    0.0  0.0     0.0  1.0  0.0
3     0.0    1.0  0.0     1.0  0.0  0.0
4     0.0    1.0  0.0     1.0  0.0  0.0
..    ...    ...  ...     ...  ...  ...
295   1.0    0.0  0.0     0.0  0.0  1.0
296   0.0    1.0  0.0     0.0  0.0  1.0
297   0.0    1.0  0.0     0.0  1.0  0.0
298   0.0    1.0  0.0     1.0  0.0  0.0
299   1.0    0.0  0.0     0.0  0.0  1.0

[300 rows x 6 columns]

In [15]:
features = pd.DataFrame(feature_array,columns=feature_labels)

In [16]:
features.head()

Blue  Green  Red  Canada   UK  USA
0   0.0    0.0  1.0     0.0  0.0  1.0
1   0.0    0.0  1.0     0.0  0.0  1.0
2   1.0    0.0  0.0     0.0  1.0  0.0
3   0.0    1.0  0.0     1.0  0.0  0.0
4   0.0    1.0  0.0     1.0  0.0  0.0

In [17]:
df_new=pd.concat([df,features],axis=1)

In [18]:
df_new.head()

Id Colour Country  Blue  Green  Red  Canada   UK  USA
0   1    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
1   2    Red     USA   0.0    0.0  1.0     0.0  0.0  1.0
2   3   Blue      UK   1.0    0.0  0.0     0.0  1.0  0.0
3   4  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0
4   5  Green  Canada   0.0    1.0  0.0     1.0  0.0  0.0

2. One Hot Encoding with Multiple Categories

In [2]:
data=pd.read_csv('mercendez.csv',usecols=['X1','X2','X3','X4','X5','X6'])
data.head()

X1  X2 X3 X4 X5 X6
0  v  at  a  d  u  j
1  t  av  e  d  y  l
2  w   n  c  d  x  j
3  t   n  f  d  x  l
4  v   n  f  d  h  d

In [ ]:
# Lets have a look at how many labels each variable has - 
for cols in data.columns:
    print(cols,': ',len(data[cols].unique()),' labels')

X1 :  27  labels
X2 :  44  labels
X3 :  7  labels
X4 :  4  labels
X5 :  29  labels
X6 :  12  labels


In [ ]:
# How many columns we will have after one-hot encoding

pd.get_dummies(data,drop_first=True).shape

(4209, 117)

In [5]:
# Top 20 most frequncy categories for variable X2

data.X2.value_counts().sort_values(ascending=False).head(20)

X2
as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
k       25
i       25
b       21
ao      20
z       19
ag      19
Name: count, dtype: int64

In [6]:
# A list of 10 most frequent categories of variable

top_10 = [x for x in data.X2.value_counts().sort_values(ascending=False).head(10).index]

top_10

['as', 'ae', 'ai', 'm', 'ak', 'r', 'n', 's', 'f', 'e']

In [8]:
#We make 10 binary variables

for label in top_10:
    data[label]=np.where(data['X2']==label,1,0)

data[['X2']+top_10].head(40)

X2  as  ae  ai  m  ak  r  n  s  f  e
0   at   0   0   0  0   0  0  0  0  0  0
1   av   0   0   0  0   0  0  0  0  0  0
2    n   0   0   0  0   0  0  1  0  0  0
3    n   0   0   0  0   0  0  1  0  0  0
4    n   0   0   0  0   0  0  1  0  0  0
5    e   0   0   0  0   0  0  0  0  0  1
6    e   0   0   0  0   0  0  0  0  0  1
7   as   1   0   0  0   0  0  0  0  0  0
8   as   1   0   0  0   0  0  0  0  0  0
9   aq   0   0   0  0   0  0  0  0  0  0
10   r   0   0   0  0   0  1  0  0  0  0
11   e   0   0   0  0   0  0  0  0  0  1
12  ai   0   0   1  0   0  0  0  0  0  0
13   e   0   0   0  0   0  0  0  0  0  1
14  as   1   0   0  0   0  0  0  0  0  0
15  ak   0   0   0  0   1  0  0  0  0  0
16   e   0   0   0  0   0  0  0  0  0  1
17  as   1   0   0  0   0  0  0  0  0  0
18   m   0   0   0  1   0  0  0  0  0  0
19  ak   0   0   0  0   1  0  0  0  0  0
20   m   0   0   0  1   0  0  0  0  0  0
21  as   1   0   0  0   0  0  0  0  0  0
22   a   0   0   0  0   0  0  0  0  0  0
23   m   0   0   0  1   0  0  0  0  0  0
24  ak   0   0   0  0   1  0  0  0  0  0
25   m   0   0   0  1   0  0  0  0  0  0
26  as   1   0   0  0   0  0  0  0  0  0
27  as   1   0   0  0   0  0  0  0  0  0
28  as   1   0   0  0   0  0  0  0  0  0
29   m   0   0   0  1   0  0  0  0  0  0
30  as   1   0   0  0   0  0  0  0  0  0
31  as   1   0   0  0   0  0  0  0  0  0
32   m   0   0   0  1   0  0  0  0  0  0
33  as   1   0   0  0   0  0  0  0  0  0
34  as   1   0   0  0   0  0  0  0  0  0
35  ai   0   0   1  0   0  0  0  0  0  0
36  as   1   0   0  0   0  0  0  0  0  0
37   k   0   0   0  0   0  0  0  0  0  0
38  as   1   0   0  0   0  0  0  0  0  0
39  as   1   0   0  0   0  0  0  0  0  0